name: "Continous integration for summarize_ai application"

on:
  push:
    branches:
      - 'main'
      - 'release/*'
    pull_request:
        branches:
          - 'main'
    workflow_dispatch:

jobs:
  build:
    name: "Build and run unit tests on application api"
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repository
        uses: action/checkout@v2

      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      -
        name: Install dependencies
        run: |
          make install

      -
        name: Lint code
        run: |
          make lint

      -
        name: Test application
        run: |
          make test

      -
        name: Format code
        run: |
          make format

  containerize:
    name: Create a docker image of the application and push to Siraluda repo
    runs-on: ubuntu-latest
    needs: build

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: siraluda/summarize_ai:latest
